-- READ ONLY. Select the hosted POS database in phpMyAdmin, then run these checks.
SHOW CREATE TABLE products;
SHOW INDEX FROM products;

SELECT id, COUNT(*) AS copies
FROM products GROUP BY id
HAVING id IS NULL OR id <= 0 OR COUNT(*) > 1;

SELECT sku, COUNT(*) AS copies FROM products
WHERE sku IS NOT NULL AND sku <> '' GROUP BY sku HAVING COUNT(*) > 1;

SELECT TABLE_NAME, COLUMN_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME = 'products';

SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY, EXTRA
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND COLUMN_NAME = 'id'
ORDER BY TABLE_NAME;
